name: pocket-js-server

services:
  pg:
    image: bitnami/postgresql:latest
    ports: 
      - "4420:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit  